(cl:defpackage crazypkg-msg
  (:use )
  (:export
   "<MOTORCOMMANDS>"
   "MOTORCOMMANDS"
   "<SAMPLETIMEPARAM>"
   "SAMPLETIMEPARAM"
   "<VICONDATA>"
   "VICONDATA"
   "<CONTROLLEROUTPUTPACKAGE>"
   "CONTROLLEROUTPUTPACKAGE"
   "<CONTROLLERPARAM>"
   "CONTROLLERPARAM"
   "<POSITIONSETPOINT>"
   "POSITIONSETPOINT"
  ))

