# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from crazypkg/ControllerOutputPackage.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ControllerOutputPackage(genpy.Message):
  _md5sum = "0b6ac24b895aa888e2867a1a58e54d9e"
  _type = "crazypkg/ControllerOutputPackage"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 roll
float32 pitch
float32 yaw
uint16 thrust
uint16 motorCmd1
uint16 motorCmd2
uint16 motorCmd3
uint16 motorCmd4
uint8 onboardControllerType


"""
  __slots__ = ['roll','pitch','yaw','thrust','motorCmd1','motorCmd2','motorCmd3','motorCmd4','onboardControllerType']
  _slot_types = ['float32','float32','float32','uint16','uint16','uint16','uint16','uint16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       roll,pitch,yaw,thrust,motorCmd1,motorCmd2,motorCmd3,motorCmd4,onboardControllerType

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControllerOutputPackage, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.thrust is None:
        self.thrust = 0
      if self.motorCmd1 is None:
        self.motorCmd1 = 0
      if self.motorCmd2 is None:
        self.motorCmd2 = 0
      if self.motorCmd3 is None:
        self.motorCmd3 = 0
      if self.motorCmd4 is None:
        self.motorCmd4 = 0
      if self.onboardControllerType is None:
        self.onboardControllerType = 0
    else:
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.thrust = 0
      self.motorCmd1 = 0
      self.motorCmd2 = 0
      self.motorCmd3 = 0
      self.motorCmd4 = 0
      self.onboardControllerType = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3f5HB().pack(_x.roll, _x.pitch, _x.yaw, _x.thrust, _x.motorCmd1, _x.motorCmd2, _x.motorCmd3, _x.motorCmd4, _x.onboardControllerType))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 23
      (_x.roll, _x.pitch, _x.yaw, _x.thrust, _x.motorCmd1, _x.motorCmd2, _x.motorCmd3, _x.motorCmd4, _x.onboardControllerType,) = _get_struct_3f5HB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3f5HB().pack(_x.roll, _x.pitch, _x.yaw, _x.thrust, _x.motorCmd1, _x.motorCmd2, _x.motorCmd3, _x.motorCmd4, _x.onboardControllerType))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 23
      (_x.roll, _x.pitch, _x.yaw, _x.thrust, _x.motorCmd1, _x.motorCmd2, _x.motorCmd3, _x.motorCmd4, _x.onboardControllerType,) = _get_struct_3f5HB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f5HB = None
def _get_struct_3f5HB():
    global _struct_3f5HB
    if _struct_3f5HB is None:
        _struct_3f5HB = struct.Struct("<3f5HB")
    return _struct_3f5HB
