safeController:    "SafeControllerService/RateController"
demoController:    "DemoControllerService/DemoController"
studentController: "StudentControllerService/StudentController"
mpcController:     "MpcControllerService/MpcController"
remoteController:  "RemoteControllerService/RemoteController"
tuningController:  "TuningControllerService/TuningController"

strictSafety: true
angleMargin: 0.8

battery_threshold_while_flying: 2.8       # in V
battery_threshold_while_motors_off: 3.30  # in V
battery_polling_period: 100               # in ms

