TeamName: 'Two'
CrazyFlieName: "cfThree"
CrazyFlieAddress: "radio://0/72/2M"
SafeController: ""
SafeControllerType: ""
CustomController: ""
CustomControllerType: ""

#controllertypes to add with adjustable
#motor, angle and rate
