safeController: "SafeControllerService/RateController"
customController: "CustomControllerService/CustomController"
strictSafety: true
angleMargin: 0.6
battery_threshold_while_flying: 2.9      # in V
battery_threshold_while_motors_off: 3.34 # in V
battery_polling_period: 100         # in ms

