/* Auto-generated by genmsg_cpp for file /home/crazyfly/crazyflie_ws/sandbox/crazypkg/msg/ControllerParam.msg */
#ifndef CRAZYPKG_MESSAGE_CONTROLLERPARAM_H
#define CRAZYPKG_MESSAGE_CONTROLLERPARAM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace crazypkg
{
template <class ContainerAllocator>
struct ControllerParam_ {
  typedef ControllerParam_<ContainerAllocator> Type;

  ControllerParam_()
  : crazyControllerType(0)
  , basicControllerType(0)
  , paramType(0)
  , value(0.0)
  {
  }

  ControllerParam_(const ContainerAllocator& _alloc)
  : crazyControllerType(0)
  , basicControllerType(0)
  , paramType(0)
  , value(0.0)
  {
  }

  typedef int16_t _crazyControllerType_type;
  int16_t crazyControllerType;

  typedef int16_t _basicControllerType_type;
  int16_t basicControllerType;

  typedef int16_t _paramType_type;
  int16_t paramType;

  typedef double _value_type;
  double value;


  typedef boost::shared_ptr< ::crazypkg::ControllerParam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazypkg::ControllerParam_<ContainerAllocator>  const> ConstPtr;
}; // struct ControllerParam
typedef  ::crazypkg::ControllerParam_<std::allocator<void> > ControllerParam;

typedef boost::shared_ptr< ::crazypkg::ControllerParam> ControllerParamPtr;
typedef boost::shared_ptr< ::crazypkg::ControllerParam const> ControllerParamConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::crazypkg::ControllerParam_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::crazypkg::ControllerParam_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace crazypkg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::crazypkg::ControllerParam_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::crazypkg::ControllerParam_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::crazypkg::ControllerParam_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4b31db51200388b6429184e9d083fa8c";
  }

  static const char* value(const  ::crazypkg::ControllerParam_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4b31db51200388b6ULL;
  static const uint64_t static_value2 = 0x429184e9d083fa8cULL;
};

template<class ContainerAllocator>
struct DataType< ::crazypkg::ControllerParam_<ContainerAllocator> > {
  static const char* value() 
  {
    return "crazypkg/ControllerParam";
  }

  static const char* value(const  ::crazypkg::ControllerParam_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::crazypkg::ControllerParam_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 crazyControllerType\n\
int16 basicControllerType\n\
int16 paramType\n\
float64 value\n\
\n\
";
  }

  static const char* value(const  ::crazypkg::ControllerParam_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::crazypkg::ControllerParam_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::crazypkg::ControllerParam_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.crazyControllerType);
    stream.next(m.basicControllerType);
    stream.next(m.paramType);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct ControllerParam_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazypkg::ControllerParam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::crazypkg::ControllerParam_<ContainerAllocator> & v) 
  {
    s << indent << "crazyControllerType: ";
    Printer<int16_t>::stream(s, indent + "  ", v.crazyControllerType);
    s << indent << "basicControllerType: ";
    Printer<int16_t>::stream(s, indent + "  ", v.basicControllerType);
    s << indent << "paramType: ";
    Printer<int16_t>::stream(s, indent + "  ", v.paramType);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CRAZYPKG_MESSAGE_CONTROLLERPARAM_H

