/* Auto-generated by genmsg_cpp for file /home/crazyfly/crazyflie_ws/sandbox/crazypkg/msg/PositionSetpoint.msg */
#ifndef CRAZYPKG_MESSAGE_POSITIONSETPOINT_H
#define CRAZYPKG_MESSAGE_POSITIONSETPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace crazypkg
{
template <class ContainerAllocator>
struct PositionSetpoint_ {
  typedef PositionSetpoint_<ContainerAllocator> Type;

  PositionSetpoint_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , yaw(0.0)
  {
  }

  PositionSetpoint_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , yaw(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _yaw_type;
  double yaw;


  typedef boost::shared_ptr< ::crazypkg::PositionSetpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazypkg::PositionSetpoint_<ContainerAllocator>  const> ConstPtr;
}; // struct PositionSetpoint
typedef  ::crazypkg::PositionSetpoint_<std::allocator<void> > PositionSetpoint;

typedef boost::shared_ptr< ::crazypkg::PositionSetpoint> PositionSetpointPtr;
typedef boost::shared_ptr< ::crazypkg::PositionSetpoint const> PositionSetpointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::crazypkg::PositionSetpoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::crazypkg::PositionSetpoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace crazypkg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::crazypkg::PositionSetpoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::crazypkg::PositionSetpoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::crazypkg::PositionSetpoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "52d0ade995d52d04cae303675aa442a7";
  }

  static const char* value(const  ::crazypkg::PositionSetpoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x52d0ade995d52d04ULL;
  static const uint64_t static_value2 = 0xcae303675aa442a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazypkg::PositionSetpoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "crazypkg/PositionSetpoint";
  }

  static const char* value(const  ::crazypkg::PositionSetpoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::crazypkg::PositionSetpoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 yaw\n\
\n\
";
  }

  static const char* value(const  ::crazypkg::PositionSetpoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::crazypkg::PositionSetpoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::crazypkg::PositionSetpoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct PositionSetpoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazypkg::PositionSetpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::crazypkg::PositionSetpoint_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CRAZYPKG_MESSAGE_POSITIONSETPOINT_H

