# The name the controller services advertised by
# each of the controller nodes.
defaultController:  "DefaultControllerService/DefaultController"
studentController:  "StudentControllerService/StudentController"
tuningController:   "TuningControllerService/TuningController"
pickerController:   "PickerControllerService/PickerController"
templateController: "TemplateControllerService/TemplateController"

testMotorsController: "TestMotorsControllerService/TestMotorsController"

# The name of the service advertised by the Default
# Controller for requests manoeuvres to be performed
defaultController_requestManoeuvre: "DefaultControllerService/RequestManoeuvre"

# The name of the service advertised by the Default
# Controller for requests manoeuvres to be performed
templateController_requestManoeuvre: "TemplateControllerService/RequestManoeuvre"

# Flag for whether to use angle for switching
# to the Default Controller
isEnabled_strictSafety: true
maxTiltAngle_for_strictSafety_degrees: 70

# Number of consecutive occulsions that will deem the
# object as "long-term" occuled
consecutive_occulsions_threshold: 30

# Time out duration after which Mocap is considered unavailable
mocap_timeout_duration: 2.0

# Flag for whether the take-off should be performed
# with the default controller
shouldPerfom_takeOff_with_defaultController: false

# Flag for whether the landing should be performed
# with the default controller
shouldPerfom_landing_with_defaultController: false