#!/bin/bash

if [ "$#" -ne 4 ] 
then echo "usage: safe_controller_setpoint <x> <y> <z> <yaw>"
else rostopic pub -1 /SafeControllerService/Setpoint d_fall_pps/Setpoint "{x: $1, y: $2, z: $3, yaw: $4}";
fi

